[versions]
junit = "5.8.2"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.23.1" }
commons-cli = { group = "commons-cli", name = "commons-cli", version = "1.5.0" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.16" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.16" }

[plugins]
sonarqube = { id = "org.sonarqube", version = "6.0.1.5171" }